services:
  booking-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - NODE_ENV=production
      - PORT=80
      - PAYMONGO_SECRET_KEY=${PAYMONGO_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
    restart: always
